language: go

go:
  - 1.13.x

env:
  - CODECOV_TOKEN="de107f56-343c-401e-b84d-5599eadc48a9"

before_install:
  - go get -t -v ./...

script:
  - go test -v ./... --tags integration -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)